"""
Claim pydantic models
"""
from datetime import datetime
from typing import Optional, Dict, Any, List
from enum import Enum
from pydantic import BaseModel, Field, ConfigDict
from utils import hexhash
class ContentType(str, Enum):
    """Type of content being claimed."""
    IMAGE = "image"
    VIDEO = "video"
    DOCUMENT = "document"

class VerityClaim(BaseModel):
    """
    Core model representing a verifiable claim issued by an organization.
    This is the object that will be signed and anchored.
    """
    # --- Claim Identity & Metadata ---
    claim_id: str = Field(
        ...,
        description="Unique identifier for this claim (e.g., a UUID or hash)."
    )
    context: List[str] = Field(
        default=["https://verity.foundation/contexts/claim/v1"],
        description="JSON-LD contexts for semantic understanding."
    )
    type: List[str] = Field(
        default=["VerifiableCredential", "VerityClaim"],
        description="The type of this credential."
    )
    issuance_date: datetime = Field(
        default_factory=datetime.now,
        description="When the claim was issued."
    )
    expiration_date: Optional[datetime] = Field(
        None,
        description="Optional date after which the claim is no longer valid."
    )

    # --- Issuer (Who is making the claim) ---
    issuer: Dict[str, str] = Field(
        ...,
        description="The DID of the issuing organization and optional specific key.",
        examples=[{"id": "did:verity:gov:demo-commission", "signed_by": "#master-key-1"}]
    )

    # --- Credential Subject (The actual content being attested) ---
    credential_subject: Dict[str, Any] = Field(
        ...,
        description="The core content/statement of the claim.",
        examples=[{
            "id": "urn:uuid:target-content-123",
            "type": "ElectionResult",
            "title": "2024 Presidential Election - Final Tally",
            "summary": "The final certified results for the 2024 presidential election...",
            "content_url": "https://elections.demo/results.pdf",
            "authority": "National Electoral Commission"
        }]
    )

    # --- Content Integrity & Platform Verification ---
    content_hash: str = Field(
        ...,
        description="Cryptographic hash (e.g., SHA-256) of the original content file.",
        examples=["sha256:a1b2c3..."]
    )
    content_type: ContentType
    platform_hashes: Optional[Dict[str, Dict[str, str]]] = Field(
        None,
        description="Perceptual or format-specific hashes for different platforms.",
        examples=[{
            "twitter": {"perceptual_hash": "phash:1234abc", "format": "jpeg_medium"},
            "facebook": {"perceptual_hash": "phash:5678def", "format": "webp_high"}
        }]
    )

    # --- Proof & Anchoring (To be filled after signing/anchoring) ---
    proof: Optional[Dict[str, Any]] = Field(
        None,
        description="Cryptographic signature and anchoring proof. Added by the system.",
        examples=[{
            "type": "Ed25519Signature2020",
            "created": "2024-01-20T14:30:00Z",
            "verification_method": "did:verity:gov:demo-commission#master-key-1",
            "proof_value": "z4oey5q...",  # The actual signature
            "anchors": [
                {
                    "type": "VerityBatchMerkleAnchor",
                    "batch_id": 427,
                    "merkle_proof": ["0xabc...", "0xdef..."],
                    "transaction_receipt": "0x123..."  # Mock for demo
                }
            ]
        }]
    )

    # --- Verification Metadata (For the demo UI) ---
    verification_url: Optional[str] = Field(
        None,
        description="The direct URL to verify this claim. Generated by the system."
    )
    model_config = ConfigDict(
        use_enum_values=True
    )

    def generate_claim_id(self) -> str:
        """Helper to generate a unique ID based on content and issuer."""
        data = f"{self.issuer['id']}{self.content_hash}{self.issuance_date.isoformat()}"

        return f"claim_{hexhash(data.encode())[:16]}"
